# Generated by Django 6.0.3 on 2026-04-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/default_avatar.png', null=True, upload_to='profiles/%Y/%m/'),
        ),
    ]
